# Generated by Django 3.1.3 on 2021-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sender_name', models.CharField(max_length=225)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(max_length=225)),
                ('sender_address', models.CharField(max_length=225)),
                ('receiver_name', models.CharField(max_length=225)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_phone', models.CharField(max_length=225)),
                ('receiver_address', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
